### ISSUE TITLE
Vod-ConvertVodFile接口始终返回4100错误

### ISSUE THREAD

**Issue by uzaidabin** [QcloudApi/qcloudapi-sdk-dotnet#1]
以下是调用API的代码，SecretKey已隐藏
SortedDictionary<string, object> requestParams = new SortedDictionary<string, object>(StringComparer.Ordinal);
            requestParams.Add("SecretId", "AKID22Wu9E83jCTluvrV0KVBj5EEnEWfsOAv");
            requestParams.Add("SecretKey", "我的SecretKey");
            requestParams.Add("RequestMethod", "GET");
            requestParams.Add("DefaultRegion", "gz");
 QCloudAPIModuleCenter module = new QCloudAPIModuleCenter(new Vod(), requestParams);
            SortedDictionary<String, Object> Params = new SortedDictionary<String, Object>();
            Params.Add("fileId", 9031868222887390404);
           var result = module.Call("ConvertVodFile", Params);
result 始终返回4100，这个sdk的鉴权有误？

**Comment by qq1211178784** [comment]
好吧，关了，看着不爽
